<?php


class Point3D extends Point2D
{
    public $z;
    public function __construct($x, $y, $z)
    {
        parent::__construct($x, $y);
        $this->z = $z;
    }
    public function getZ()
    {
        return $this->z;
    }
    public function setZ($z)
    {
        $this->z = $z;
    }
    public function toString()
    {
        return parent::toString() . ' Point3D '; // TODO: Change the autogenerated stub
    }

}